Do not include <linux/ptrace.h>
<linux/ptrace.h> conflicts with <sys/ptrace.h> on recent
toolchains and including the former is enough.

In file included from Ptrace.hsc:10:0:
/usr/include/linux/ptrace.h:58:8: error:
redefinition of ‘struct ptrace_peeksiginfo_args’
 struct ptrace_peeksiginfo_args {
        ^
In file included from Ptrace.hsc:9:0:
/usr/include/sys/ptrace.h:191:8: note: originally defined here
 struct ptrace_peeksiginfo_args
        ^